import type { Metadata } from "next";
import { Kanit, Anta } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Navbar from "@/components/Sections/Navbar";

const kanit = Kanit({
  weight: ["400", "500", "700"],
  subsets: ["thai", "latin"],
  display: "swap",
});

const anta = Anta({
  variable: "--font-anta",
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className} ${anta.variable} antialiased`}>
        <Navbar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
